version: '3.8'
services:
  backend:
    build:
      context: ./packages/server
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - $BACK_PORT:$BACK_PORT
    environment:
      - PORT=$BACK_PORT
      - MELI_API=$MELI_API
      - SIGNATURE_NAME=$SIGNATURE_NAME
      - SIGNATURE_LAST_NAME=$SIGNATURE_LAST_NAME
  frontend:
    build:
      context: ./packages/client
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - $FRONT_PORT:$FRONT_PORT
    environment:
      - PORT=$FRONT_PORT
      - NEXT_PUBLIC_MY_API=http://localhost:$BACK_PORT/api
